version: "3"
services:
  client:
    image: "souhardya/multi-client-1"
    mem_limit: 128m
    hostname: client
  server:
    image: "souhardya/multi-server-1"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "souhardya/multi-worker-1"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "souhardya/multi-nginx-1"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"