name: Deploy Frontend
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t souhardya/react-test -f react-app/Dockerfile.dev react-app/.
      - run: docker run -e CI=true souhardya/react-test npm test
 
      - name: Generate deployment package
        run: zip -r deploy.zip ./react-app/* -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-react
          environment_name: Docker-react-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-730335432818
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip